-- Social Post Batch Grouping Migration
-- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/cfkovdyvmbnnyzihqanp/sql/new
--
-- Adds batch_id and batch_label to social_posts so posts generated by the
-- Content Atomizer in a single run can be grouped and reviewed together.

ALTER TABLE social_posts
  ADD COLUMN IF NOT EXISTS batch_id    UUID DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS batch_label TEXT DEFAULT NULL;

-- Fast lookup when rendering the Batches view (groups by client + batch)
CREATE INDEX IF NOT EXISTS idx_social_posts_batch
  ON social_posts(client_id, batch_id)
  WHERE batch_id IS NOT NULL;
