import { getContentIdeas } from '@/lib/data'
import { ContentIdeasList } from '@/components/content/content-ideas-list'
import { RealtimeRefresh } from '@/components/content/realtime-refresh'

interface ContentPageProps {
  params: Promise<{ clientId: string }>
}

export default async function ContentPage({ params }: ContentPageProps) {
  const { clientId } = await params
  const ideas = await getContentIdeas(clientId)

  return (
    <div className="space-y-6">
      <RealtimeRefresh table="content_ideas" clientId={clientId} />
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Content Ideas</h1>
        <p className="text-muted-foreground">
          All content ideas generated by Claude — from prompts, research, and atomization
        </p>
      </div>
      <ContentIdeasList ideas={ideas} clientId={clientId} />
    </div>
  )
}
